# server configuration json
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-configjson
data:
  panda_server_config.json: |-
{{ .Files.Get "panda_server_config.json" | indent 4}}

{{- if .Values.hostcerts.enabled }}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "server.fullname" . }}-certs
binaryData:
  {{- range $path, $_ := .Files.Glob "cert/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
{{- end }}

---
# server env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-env
data:
  PANDA_URL: "https://{{ include "server.fullname" .}}:{{ .Values.service.httpsPort }}/server/panda"
  PANDA_URL_SSL: "https://{{ include "server.fullname" .}}:{{ .Values.service.httpsPort }}/server/panda"
  {{- if .Values.authIdToken }}
  PANDA_VERIFY_HOST: "off"
  PANDA_AUTH: "oidc"
  PANDA_AUTH_ID_TOKEN: {{ .Values.authIdToken }}
  PANDA_AUTH_VO: {{ .Values.authVO }}
  PANDA_ACTIVEMQ_LIST: {{ join "," .Values.activemq.serverList }}
  PANDA_ACTIVEMQ_PASSWD_panda: {{ .Values.activemq.basePasswd }}_panda
  PANDA_ACTIVEMQ_PASSWD_jedi: {{ .Values.activemq.basePasswd }}_jedi
  {{- end }}
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost,{{ include "server.fullname" . }}"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost,{{ include "server.fullname" . }}"
  {{- end }}
  {{- end }}
  {{- if .Values.noRoot }}
  PANDA_NO_ROOT: "1"
  {{- end }}
  {{- if .Values.rucioAccount }}
  PANDA_RUCIO_ACCOUNT: "{{ .Values.rucioAccount }}"
  {{- end }}
---
# auth
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-auth
data:
  {{- range $path, $_ := .Files.Glob "auth/**_auth_config.json" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path }}
  {{- end }}

---
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}
