# harvester configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-configmap
data:
  {{- range $path, $_ := .Files.Glob "conf/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4}}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-envs
  labels:
    {{- include "main.labels" . | nindent 4 }}
data:
  # IAM_JAVA_OPTS: "-Dspring.profiles.active={{ .Values.iam.profiles }} -Dspring.data.rest.basePath=/iam -Dserver.servlet.context-path=/iam -Dlog4j2.formatMsgNoLookups=true"
  IAM_JAVA_OPTS: "-Dspring.profiles.active={{ .Values.iam.profiles }} -Dlog4j2.formatMsgNoLookups=true"

  {{- if not .Values.secret.enabled }}
  IAM_CILOGON_CLIENT_ID: {{ .Values.iam.cilogon_client_id}}
  IAM_CILOGON_CLIENT_SECRET: {{ .Values.iam.cilogon_client_secret}}
  {{- end }}

  IAM_PORT: "8080"

  IAM_ORGANISATION_NAME: {{ .Values.iam.organization}}
  IAM_TOPBAR_TITLE: "PanDA Rubin"
  IAM_ACCESS_TOKEN_INCLUDE_AUTHN_INFO: "true"
  IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY: "hidden"
  IAM_CLIENT_REGISTRATION_ALLOW_FOR: REGISTERED_USERS
  IAM_LOCAL_AUTHN_ENABLED_FOR: vo-admins
  IAM_REGISTRATION_REQUIRE_EXTERNAL_AUTHENTICATION: "true"
  IAM_LOGO_URL: "https://atlpan.web.cern.ch/atlpan/PanDA-rev-logo-300.jpg"
  IAM_LOGO_HEIGHT: "200"
  IAM_LOGO_WIDTH: "200"
  IAM_REGISTRATION_OIDC_ISSUER: "https://cilogon.org"

  IAM_BASE_URL: "https://panda-iam-dev.cern.ch"
  IAM_ISSUER: "https://panda-iam-dev.cern.ch"
  IAM_USE_FORWARDED_HEADERS: "true"
  IAM_KEY_STORE_LOCATION: "file:///indigo-iam/config//iam-keystore.jwks"

  IAM_MAIL_HOST: "smtp.cern.ch"
  IAM_MAIL_PORT: "587"
  IAM_NOTIFICATION_FROM: "panda-doma-no-reply@cern.ch"
  IAM_NOTIFICATION_ADMIN_ADDRESS: "panda-doma-admins@cern.ch"
