# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  POSTGRES_SCHEMA: {{ .Values.database.schema }}
  {{- if .Values.noRoot }}
  PGDATA: "/tmp/pg_volume/data"
  {{- end }}