# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  POSTGRES_SCHEMA: {{ .Values.database.schema }}
  {{- if .Values.noRoot }}
  PGDATA: "/tmp/pg_volume/data"
  {{- end }}

  IDDS_DATABASE_NAME: "{{ .Values.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.database.schema}}"
  {{- if .Values.database.host }}
  IDDS_DATABASE_HOST: "{{ .Values.database.host}}"
  {{- else }}
  IDDS_DATABASE_HOST: {{.Release.Name}}-postgres
  {{- end }}
