# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"

rest:
  enabled: true
  image:
    tag: "2.2.8"

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 16Gi

postgres:
  enabled: true
  image:
    tag: "13.6"

  database:
    name: "idds_db"
    user: "idds"
    password: "MyPass123"
    schema: "doma_idds"
    host: ""

  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 16Gi
