# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activemq.fullname" . }}-sandbox
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activemq.fullname" . }}-env
data:
  ACTIVEMQ_BASE_PASSWD: {{ .Values.basePasswd }}
  ACTIVEMQ_CHANNELS: {{ join ";" .Values.channels }}
  ACTIVEMQ_ACCOUNTS: {{ join ";" .Values.accounts }}
