# Default values for panda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"

jedi:
  # enable JEDI
  enabled: true

  # container image and tag
  image:
    tag: "0.0.16"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

server:
  # enable the PanDA server
  enabled: true

  # container image and tag
  image:
    tag: "0.0.45"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

  # copy host certs from local
  #hostcerts:
  #  enabled: false

  # host name of the PanDA server for external access
  hostName: "FIXME"

  # use Route class to expose the service
  route:
    enabled: false

    
  # use Ingress class to expose the service  
  ingress:
    enabled: false
    hosts:
      - domain: "FIXME"
        hostOverride: ""
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "FIXME"
        hosts:
          - domain: "FIXME"
            hostOverride: "FIXME"

  # http/s proxy if containers need it to access external services
  #httpsProxy: "http://proxy.sdcc.bnl.local:3128"
  #httpProxy: "http://proxy.sdcc.bnl.local:3128"

  # run containers with no-root PID e.g. for OKD
  #noRoot: true

  # rucio account
  # rucioAccount: iddsv1

postgres:
  # enable the database
  enabled: true

  # container image and tag
  image:
    tag: "0.0.14"
    #tag: "main"

  # PV with selector support
  #persistentvolume:
  #    selector: false
