# Default values for panda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jedi:
  # enable JEDI
  enabled: true

  # container image and tag
  image:
    tag: "0.0.13"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

server:
  # enable the PanDA server
  enabled: true

  # container image and tag
  image:
    tag: "0.0.41"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

  # copy host certs from local
  #hostcerts:
  #  enabled: false

  # host name of the PanDA server for external access
  hostName: "FIXME"

  # use Route class to expose the service
  route:
    enabled: false

    
  # use Ingress class to expose the service  
  ingress:
    enabled: false
    hosts:
      - domain: "FIXME"
        hostOverride: ""
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "FIXME"
        hosts:
          - domain: "FIXME"
            hostOverride: "FIXME"

  # ID token of the PanDA service account
  authIdToken: "FIXME"

  # VO (. role) of the ID token
  authVO: "panda_dev.production"

  # http/s proxy if containers need it to access external services
  #httpsProxy: "http://proxy.sdcc.bnl.local:3128"
  #httpProxy: "http://proxy.sdcc.bnl.local:3128"

  # run containers with no-root PID e.g. for OKD
  #noRoot: true

  # rucio account
  # rucioAccount: iddsv1

postgres:
  # enable the database
  enabled: true

  # container image and tag
  image:
    tag: "0.0.12"
    #tag: "main"

  # PV with selector support
  #persistentvolume:
  #    selector: false


### External service config

# activeMQ
activemq:
  # hosts and ports
  serverList:
    - "activemq-dev:61613"

  # base password
  basePasswd: "ITzqWRCd"

# iDDS
idds:
  # REST hostname
  restHost: "idds-rest"

  # REST port
  restPort: 443

  # ID token of the iDDS account
  authIdToken: "FIXME"

  # VO of the ID token
  authVO: "panda_dev"

# rucio
rucio:
  # rucio host and port
  rucioHost: "sprucio01.sdcc.bnl.gov:443"

  # auth host and port
  authHost: "sprucio01.sdcc.bnl.gov:443"

  # username
  username: "iddsv1"

  # password
  password: "FIXME"

  # account
  account: "iddsv1"
