# Default values for harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

harvester:
  replicaCount: 2

  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 300Gi

  httpProxy: "http://atlsquid.slac.stanford.edu:3128"
  httpsProxy: "http://atlsquid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,panda-dev-server"

  experiment: "lsst"
  panda:
    host: "panda-dev-server:443"
  pilotcerts:
    enabled: true

mariadb:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
    size: 50Gi
