# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daemon.fullname" . }}-configmap
data:
  ACTIVEMQ_NAME: {{ include "daemon.fullname" . }}
  ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "false"
  ACTIVEMQ_ADMIN_LOGIN: {{ .Values.admin.name }}
  ACTIVEMQ_ADMIN_PASSWORD: {{ .Values.admin.password }}
  ACTIVEMQ_ENABLED_SCHEDULER: {{ .Values.scheduler.enabled | quote }}
  ACTIVEMQ_ENABLED_AUTH: {{ .Values.auth.enabled | quote }}
  ACTIVEMQ_STATIC_TOPICS: {{ .Values.topics }}
  ACTIVEMQ_STATIC_QUEUES: {{ .Values.queues }}
  ACTIVEMQ_MIN_MEMORY: {{ .Values.minmemory | quote }}
  ACTIVEMQ_MAX_MEMORY: {{ .Values.maxmemory | quote }}
  ACTIVEMQ_USER_LOGIN: {{ .Values.user.name }}
  ACTIVEMQ_USER_PASSWORD: {{ .Values.user.password }}
  ACTIVEMQ_OWNER_LOGIN: {{ .Values.owner.name }}
  ACTIVEMQ_OWNER_PASSWORD: {{ .Values.owner.password }}
  ACTIVEMQ_WRITE_LOGIN: {{ .Values.write.name }}
  ACTIVEMQ_WRITE_PASSWORD: {{ .Values.write.password }}
  ACTIVEMQ_READ_LOGIN: {{ .Values.read.name }}
  ACTIVEMQ_READ_PASSWORD: {{ .Values.read.password }}

{{- if .Values.hostcerts.enabled -}}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "daemon.fullname" . }}-certs
data:
    hostcert.pem: |-
{{ .Files.Get "hostcert.pem" | indent 8}}

    hostkey.pem: |-
{{ .Files.Get "hostkey.pem" | indent 8}}
{{- end }}
