apiVersion: v1
kind: Service
metadata:
  name: {{ include "daemon.fullname" . }}
  labels:
    {{- include "daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8161
      targetPort: port8161
      protocol: TCP
      name: port8161
    - port: 5672
      targetPort: port5672
      protocol: TCP
      name: port5672
    - port: 1883
      targetPort: port1883
      protocol: TCP
      name: port1883
    - port: 61616
      targetPort: port61616
      protocol: TCP
      name: port61616
    - port: 61613
      targetPort: port61613
      protocol: TCP
      name: port61613
    - port: 61614
      targetPort: port61614
      protocol: TCP
      name: port61614
  selector:
    {{- include "daemon.selectorLabels" . | nindent 4 }}
