---
# Source: msgsvc/charts/activemq/templates/configmap.yaml
# sandbox
apiVersion: v1
kind: ConfigMap
metadata:
  name: msgsvc-dev-activemq-sandbox
binaryData:
  activemq.xml: |-
    PCEtLQogICAgTGljZW5zZWQgdG8gdGhlIEFwYWNoZSBTb2Z0d2FyZSBGb3VuZGF0aW9uIChBU0YpIHVuZGVyIG9uZSBvciBtb3JlCiAgICBjb250cmlidXRvciBsaWNlbnNlIGFncmVlbWVudHMuICBTZWUgdGhlIE5PVElDRSBmaWxlIGRpc3RyaWJ1dGVkIHdpdGgKICAgIHRoaXMgd29yayBmb3IgYWRkaXRpb25hbCBpbmZvcm1hdGlvbiByZWdhcmRpbmcgY29weXJpZ2h0IG93bmVyc2hpcC4KICAgIFRoZSBBU0YgbGljZW5zZXMgdGhpcyBmaWxlIHRvIFlvdSB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wCiAgICAodGhlICJMaWNlbnNlIik7IHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aAogICAgdGhlIExpY2Vuc2UuICBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKCiAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKCiAgICBVbmxlc3MgcmVxdWlyZWQgYnkgYXBwbGljYWJsZSBsYXcgb3IgYWdyZWVkIHRvIGluIHdyaXRpbmcsIHNvZnR3YXJlCiAgICBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAogICAgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiAgICBTZWUgdGhlIExpY2Vuc2UgZm9yIHRoZSBzcGVjaWZpYyBsYW5ndWFnZSBnb3Zlcm5pbmcgcGVybWlzc2lvbnMgYW5kCiAgICBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KLS0+CjwhLS0gU1RBUlQgU05JUFBFVDogZXhhbXBsZSAtLT4KPGJlYW5zCiAgeG1sbnM9Imh0dHA6Ly93d3cuc3ByaW5nZnJhbWV3b3JrLm9yZy9zY2hlbWEvYmVhbnMiCiAgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIKICB4c2k6c2NoZW1hTG9jYXRpb249Imh0dHA6Ly93d3cuc3ByaW5nZnJhbWV3b3JrLm9yZy9zY2hlbWEvYmVhbnMgaHR0cDovL3d3dy5zcHJpbmdmcmFtZXdvcmsub3JnL3NjaGVtYS9iZWFucy9zcHJpbmctYmVhbnMueHNkCiAgaHR0cDovL2FjdGl2ZW1xLmFwYWNoZS5vcmcvc2NoZW1hL2NvcmUgaHR0cDovL2FjdGl2ZW1xLmFwYWNoZS5vcmcvc2NoZW1hL2NvcmUvYWN0aXZlbXEtY29yZS54c2QiPgoKICAgIDwhLS0gQWxsb3dzIHVzIHRvIHVzZSBzeXN0ZW0gcHJvcGVydGllcyBhcyB2YXJpYWJsZXMgaW4gdGhpcyBjb25maWd1cmF0aW9uIGZpbGUgLS0+CiAgICA8YmVhbiBjbGFzcz0ib3JnLnNwcmluZ2ZyYW1ld29yay5iZWFucy5mYWN0b3J5LmNvbmZpZy5Qcm9wZXJ0eVBsYWNlaG9sZGVyQ29uZmlndXJlciI+CiAgICAgICAgPHByb3BlcnR5IG5hbWU9ImxvY2F0aW9ucyI+CiAgICAgICAgICAgIDx2YWx1ZT5maWxlOiR7YWN0aXZlbXEuY29uZn0vY3JlZGVudGlhbHMucHJvcGVydGllczwvdmFsdWU+CiAgICAgICAgPC9wcm9wZXJ0eT4KICAgIDwvYmVhbj4KCiAgICA8IS0tCiAgICAgICAgVGhlIDxicm9rZXI+IGVsZW1lbnQgaXMgdXNlZCB0byBjb25maWd1cmUgdGhlIEFjdGl2ZU1RIGJyb2tlci4KICAgIC0tPgogICAgPGJyb2tlciB4bWxucz0iaHR0cDovL2FjdGl2ZW1xLmFwYWNoZS5vcmcvc2NoZW1hL2NvcmUiIGJyb2tlck5hbWU9ImxvY2FsaG9zdCIgZGF0YURpcmVjdG9yeT0iJHthY3RpdmVtcS5kYXRhfSI+CgogICAgICAgIDxkZXN0aW5hdGlvblBvbGljeT4KICAgICAgICAgICAgPHBvbGljeU1hcD4KICAgICAgICAgICAgICA8cG9saWN5RW50cmllcz4KICAgICAgICAgICAgICAgIDxwb2xpY3lFbnRyeSB0b3BpYz0iPiIgPgogICAgICAgICAgICAgICAgICAgIDwhLS0gVGhlIGNvbnN0YW50UGVuZGluZ01lc3NhZ2VMaW1pdFN0cmF0ZWd5IGlzIHVzZWQgdG8gcHJldmVudAogICAgICAgICAgICAgICAgICAgICAgICAgc2xvdyB0b3BpYyBjb25zdW1lcnMgdG8gYmxvY2sgcHJvZHVjZXJzIGFuZCBhZmZlY3Qgb3RoZXIgY29uc3VtZXJzCiAgICAgICAgICAgICAgICAgICAgICAgICBieSBsaW1pdGluZyB0aGUgbnVtYmVyIG9mIG1lc3NhZ2VzIHRoYXQgYXJlIHJldGFpbmVkCiAgICAgICAgICAgICAgICAgICAgICAgICBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlOgoKICAgICAgICAgICAgICAgICAgICAgICAgIGh0dHA6Ly9hY3RpdmVtcS5hcGFjaGUub3JnL3Nsb3ctY29uc3VtZXItaGFuZGxpbmcuaHRtbAoKICAgICAgICAgICAgICAgICAgICAtLT4KICAgICAgICAgICAgICAgICAgPHBlbmRpbmdNZXNzYWdlTGltaXRTdHJhdGVneT4KICAgICAgICAgICAgICAgICAgICA8Y29uc3RhbnRQZW5kaW5nTWVzc2FnZUxpbWl0U3RyYXRlZ3kgbGltaXQ9IjEwMDAiLz4KICAgICAgICAgICAgICAgICAgPC9wZW5kaW5nTWVzc2FnZUxpbWl0U3RyYXRlZ3k+CiAgICAgICAgICAgICAgICA8L3BvbGljeUVudHJ5PgogICAgICAgICAgICAgIDwvcG9saWN5RW50cmllcz4KICAgICAgICAgICAgPC9wb2xpY3lNYXA+CiAgICAgICAgPC9kZXN0aW5hdGlvblBvbGljeT4KCgogICAgICAgIDwhLS0KICAgICAgICAgICAgVGhlIG1hbmFnZW1lbnRDb250ZXh0IGlzIHVzZWQgdG8gY29uZmlndXJlIGhvdyBBY3RpdmVNUSBpcyBleHBvc2VkIGluCiAgICAgICAgICAgIEpNWC4gQnkgZGVmYXVsdCwgQWN0aXZlTVEgdXNlcyB0aGUgTUJlYW4gc2VydmVyIHRoYXQgaXMgc3RhcnRlZCBieQogICAgICAgICAgICB0aGUgSlZNLiBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlOgoKICAgICAgICAgICAgaHR0cDovL2FjdGl2ZW1xLmFwYWNoZS5vcmcvam14Lmh0bWwKICAgICAgICAtLT4KICAgICAgICA8bWFuYWdlbWVudENvbnRleHQ+CiAgICAgICAgICAgIDxtYW5hZ2VtZW50Q29udGV4dCBjcmVhdGVDb25uZWN0b3I9ImZhbHNlIi8+CiAgICAgICAgPC9tYW5hZ2VtZW50Q29udGV4dD4KCiAgICAgICAgPCEtLQogICAgICAgICAgICBDb25maWd1cmUgbWVzc2FnZSBwZXJzaXN0ZW5jZSBmb3IgdGhlIGJyb2tlci4gVGhlIGRlZmF1bHQgcGVyc2lzdGVuY2UKICAgICAgICAgICAgbWVjaGFuaXNtIGlzIHRoZSBLYWhhREIgc3RvcmUgKGlkZW50aWZpZWQgYnkgdGhlIGthaGFEQiB0YWcpLgogICAgICAgICAgICBGb3IgbW9yZSBpbmZvcm1hdGlvbiwgc2VlOgoKICAgICAgICAgICAgaHR0cDovL2FjdGl2ZW1xLmFwYWNoZS5vcmcvcGVyc2lzdGVuY2UuaHRtbAogICAgICAgIC0tPgogICAgICAgIDxwZXJzaXN0ZW5jZUFkYXB0ZXI+CiAgICAgICAgICAgIDxrYWhhREIgZGlyZWN0b3J5PSIke2FjdGl2ZW1xLmRhdGF9L2thaGFkYiIvPgogICAgICAgIDwvcGVyc2lzdGVuY2VBZGFwdGVyPgoKCiAgICAgICAgICA8IS0tCiAgICAgICAgICAgIFRoZSBzeXN0ZW1Vc2FnZSBjb250cm9scyB0aGUgbWF4aW11bSBhbW91bnQgb2Ygc3BhY2UgdGhlIGJyb2tlciB3aWxsCiAgICAgICAgICAgIHVzZSBiZWZvcmUgZGlzYWJsaW5nIGNhY2hpbmcgYW5kL29yIHNsb3dpbmcgZG93biBwcm9kdWNlcnMuIEZvciBtb3JlIGluZm9ybWF0aW9uLCBzZWU6CiAgICAgICAgICAgIGh0dHA6Ly9hY3RpdmVtcS5hcGFjaGUub3JnL3Byb2R1Y2VyLWZsb3ctY29udHJvbC5odG1sCiAgICAgICAgICAtLT4KICAgICAgICAgIDxzeXN0ZW1Vc2FnZT4KICAgICAgICAgICAgPHN5c3RlbVVzYWdlPgogICAgICAgICAgICAgICAgPG1lbW9yeVVzYWdlPgogICAgICAgICAgICAgICAgICAgIDxtZW1vcnlVc2FnZSBwZXJjZW50T2ZKdm1IZWFwPSI3MCIgLz4KICAgICAgICAgICAgICAgIDwvbWVtb3J5VXNhZ2U+CiAgICAgICAgICAgICAgICA8c3RvcmVVc2FnZT4KICAgICAgICAgICAgICAgICAgICA8c3RvcmVVc2FnZSBsaW1pdD0iMTAwIGdiIi8+CiAgICAgICAgICAgICAgICA8L3N0b3JlVXNhZ2U+CiAgICAgICAgICAgICAgICA8dGVtcFVzYWdlPgogICAgICAgICAgICAgICAgICAgIDx0ZW1wVXNhZ2UgbGltaXQ9IjUwIGdiIi8+CiAgICAgICAgICAgICAgICA8L3RlbXBVc2FnZT4KICAgICAgICAgICAgPC9zeXN0ZW1Vc2FnZT4KICAgICAgICA8L3N5c3RlbVVzYWdlPgoKICAgICAgICA8IS0tCiAgICAgICAgICAgIFRoZSB0cmFuc3BvcnQgY29ubmVjdG9ycyBleHBvc2UgQWN0aXZlTVEgb3ZlciBhIGdpdmVuIHByb3RvY29sIHRvCiAgICAgICAgICAgIGNsaWVudHMgYW5kIG90aGVyIGJyb2tlcnMuIEZvciBtb3JlIGluZm9ybWF0aW9uLCBzZWU6CgogICAgICAgICAgICBodHRwOi8vYWN0aXZlbXEuYXBhY2hlLm9yZy9jb25maWd1cmluZy10cmFuc3BvcnRzLmh0bWwKICAgICAgICAtLT4KICAgICAgICA8dHJhbnNwb3J0Q29ubmVjdG9ycz4KICAgICAgICAgICAgPCEtLSBET1MgcHJvdGVjdGlvbiwgbGltaXQgY29uY3VycmVudCBjb25uZWN0aW9ucyB0byAxMDAwIGFuZCBmcmFtZSBzaXplIHRvIDEwME1CIC0tPgogICAgICAgICAgICA8dHJhbnNwb3J0Q29ubmVjdG9yIG5hbWU9InN0b21wIiB1cmk9InN0b21wOi8vMC4wLjAuMDo2MTYxMz9tYXhpbXVtQ29ubmVjdGlvbnM9MTAwMCZhbXA7d2lyZUZvcm1hdC5tYXhGcmFtZVNpemU9MTA0ODU3NjAwIi8+CiAgICAgICAgPC90cmFuc3BvcnRDb25uZWN0b3JzPgoKICAgICAgICA8IS0tIGRlc3Ryb3kgdGhlIHNwcmluZyBjb250ZXh0IG9uIHNodXRkb3duIHRvIHN0b3AgamV0dHkgLS0+CiAgICAgICAgPHNodXRkb3duSG9va3M+CiAgICAgICAgICAgIDxiZWFuIHhtbG5zPSJodHRwOi8vd3d3LnNwcmluZ2ZyYW1ld29yay5vcmcvc2NoZW1hL2JlYW5zIiBjbGFzcz0ib3JnLmFwYWNoZS5hY3RpdmVtcS5ob29rcy5TcHJpbmdDb250ZXh0SG9vayIgLz4KICAgICAgICA8L3NodXRkb3duSG9va3M+CgoKICAgICAgICA8cGx1Z2lucz4KICAgICAgICAgICAgPGphYXNBdXRoZW50aWNhdGlvblBsdWdpbiBjb25maWd1cmF0aW9uPSJhY3RpdmVtcSIvPgogICAgICAgICAgICA8YXV0aG9yaXphdGlvblBsdWdpbj4KICAgICAgICAgICAgICAgIDxtYXA+CiAgICAgICAgICAgICAgICAgICAgPGF1dGhvcml6YXRpb25NYXA+CiAgICAgICAgICAgICAgICAgICAgICAgIDxhdXRob3JpemF0aW9uRW50cmllcz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIF9fX0FVVEhfRU5UUklFU19fXwogICAgICAgICAgICAgICAgICAgICAgICA8L2F1dGhvcml6YXRpb25FbnRyaWVzPgogICAgICAgICAgICAgICAgICAgIDwvYXV0aG9yaXphdGlvbk1hcD4KICAgICAgICAgICAgICAgIDwvbWFwPgogICAgICAgICAgICA8L2F1dGhvcml6YXRpb25QbHVnaW4+CiAgICAgICAgPC9wbHVnaW5zPgoKICAgIDwvYnJva2VyPgoKICAgIDwhLS0KICAgICAgICBFbmFibGUgd2ViIGNvbnNvbGVzLCBSRVNUIGFuZCBBamF4IEFQSXMgYW5kIGRlbW9zCiAgICAgICAgVGhlIHdlYiBjb25zb2xlcyByZXF1aXJlcyBieSBkZWZhdWx0IGxvZ2luLCB5b3UgY2FuIGRpc2FibGUgdGhpcyBpbiB0aGUgamV0dHkueG1sIGZpbGUKCiAgICAgICAgVGFrZSBhIGxvb2sgYXQgJHtBQ1RJVkVNUV9IT01FfS9jb25mL2pldHR5LnhtbCBmb3IgbW9yZSBkZXRhaWxzCiAgICAtLT4KICAgIDxpbXBvcnQgcmVzb3VyY2U9ImpldHR5LnhtbCIvPgoKPC9iZWFucz4KPCEtLSBFTkQgU05JUFBFVDogZXhhbXBsZSAtLT4K
  install_conf.py: |-
    IyBnZW5lcmF0ZSAqLnByb3BlcnRpZXMgYW5kIGFjdGl2ZW1xLnhtbAoKaW1wb3J0IG9zCmltcG9ydCByZQoKZHN0UGF0aCA9IG9zLnBhdGguam9pbihvcy5lbnZpcm9uWydBQ1RJVkVNUV9IT01FJ10sICdjb25mJykKCiMgYmFzZSBwYXNzd29yZApiYXNlUGFzc3dkID0gb3MuZW52aXJvbi5nZXQoJ0FDVElWRU1RX0JBU0VfUEFTU1dEJywgJ3Bhc3N3b3JkJykKCiMgYWNjb3VudHMKYWNjb3VudHMgPSBvcy5lbnZpcm9uLmdldCgnQUNUSVZFTVFfQUNDT1VOVFMnLCAnJykuc3BsaXQoJzsnKQoKIyBjaGFubmVscwpjaGFubmVscyA9IG9zLmVudmlyb24uZ2V0KCdBQ1RJVkVNUV9DSEFOTkVMUycsICcnKS5zcGxpdCgnOycpCmNoYW5uZWxzID0gW2kgZm9yIGkgaW4gY2hhbm5lbHMgaWYgaV0KCiMgcHJvcGVydGllcyBmaWxlcwp1X2ZpbGUgPSBvcGVuKG9zLnBhdGguam9pbihkc3RQYXRoLCAndXNlcnMucHJvcGVydGllcycpLCAndycpCmdfZmlsZSA9IG9wZW4ob3MucGF0aC5qb2luKGRzdFBhdGgsICdncm91cHMucHJvcGVydGllcycpLCAndycpCgphdXRoX2VudHJpZXMgPSAiIiIKPGF1dGhvcml6YXRpb25FbnRyeSBxdWV1ZT0iPiIgcmVhZD0iYWRtaW5zIiB3cml0ZT0iYWRtaW5zIiBhZG1pbj0iYWRtaW5zIiAvPgo8YXV0aG9yaXphdGlvbkVudHJ5IHRvcGljPSI+IiByZWFkPSJhZG1pbnMiIHdyaXRlPSJhZG1pbnMiIGFkbWluPSJhZG1pbnMiIC8+CjxhdXRob3JpemF0aW9uRW50cnkgdG9waWM9IkFjdGl2ZU1RLkFkdmlzb3J5Lj4iIHJlYWQ9InVzZXJzIiB3cml0ZT0idXNlcnMiIGFkbWluPSJ1c2VycyIgLz4KIiIiCgojIGFkbWluIGFuZCB1c2Vycwp1X2ZpbGUud3JpdGUoJ3N5c3RlbT17fVxuJy5mb3JtYXQoYmFzZVBhc3N3ZCkpCmdfZmlsZS53cml0ZSgnYWRtaW5zPXN5c3RlbVxuJykKZ19maWxlLndyaXRlKCd1c2Vycz17fVxuJy5mb3JtYXQoJywnLmpvaW4oYWNjb3VudHMpKSkKCgojIGRlZmluZSBhY2NvdW50cwpmb3IgYWNjb3VudCBpbiBhY2NvdW50czoKICAgIHVfZmlsZS53cml0ZSgnezB9PXsxfV97MH1cbicuZm9ybWF0KGFjY291bnQsIGJhc2VQYXNzd2QpKQogICAgZ19maWxlLndyaXRlKCd7MH09c3lzdGVtLHswfVxuJy5mb3JtYXQoYWNjb3VudCkpCgojIGRlZmluZSByZWFkL3dyaXRlL293bmVyIHVzZXJzIHBlciBjaGFubmVsCmZvciBjaGFubmVsX2RlZiBpbiBjaGFubmVsczoKICAgIGNoYW5uZWwsIHdfYWNjcywgcl9hY2NzID0gY2hhbm5lbF9kZWYuc3BsaXQoJzonKQogICAgYV9hY2NzID0gInVzZXJzIgogICAgYXV0aF9lbnRyaWVzICs9ICIiIjxhdXRob3JpemF0aW9uRW50cnkgcXVldWU9Int9Lj4iIHJlYWQ9Int9IiB3cml0ZT0ie30iIGFkbWluPSJ7fSIgLz5cbiIiIi5cCiAgICAgICAgZm9ybWF0KGNoYW5uZWwsIHJfYWNjcywgd19hY2NzLCBhX2FjY3MpCiAgICBhdXRoX2VudHJpZXMgKz0gIiIiPGF1dGhvcml6YXRpb25FbnRyeSB0b3BpYz0ie30uPiIgcmVhZD0ie30iIHdyaXRlPSJ7fSIgYWRtaW49Int9IiAvPlxuIiIiLiBcCiAgICAgICAgZm9ybWF0KGNoYW5uZWwsIHJfYWNjcywgd19hY2NzLCBhX2FjY3MpCgojIGFjdGl2ZW1xLnhtbApzY3JpcHRfZGlyID0gb3MucGF0aC5hYnNwYXRoKG9zLnBhdGguZGlybmFtZShfX2ZpbGVfXykpCndpdGggb3Blbihvcy5wYXRoLmpvaW4oc2NyaXB0X2RpciwgJ2FjdGl2ZW1xLnhtbCcpKSBhcyBzcmNfZjoKICAgIGFjdGl2ZW1xX3htbCA9IHNyY19mLnJlYWQoKQogICAgbSA9IHJlLnNlYXJjaChyJyhccyspX19fQVVUSF9FTlRSSUVTX19fJywgYWN0aXZlbXFfeG1sKQogICAgaWYgbToKICAgICAgICBhdXRoX2VudHJpZXMgPSBhdXRoX2VudHJpZXMucmVwbGFjZSgnXG4nLCBtLmdyb3VwKDEpKQogICAgICAgIGFjdGl2ZW1xX3htbCA9IGFjdGl2ZW1xX3htbC5yZXBsYWNlKCdfX19BVVRIX0VOVFJJRVNfX18nLCBhdXRoX2VudHJpZXMpCiAgICB3aXRoIG9wZW4ob3MucGF0aC5qb2luKGRzdFBhdGgsICdhY3RpdmVtcS54bWwnKSwgJ3cnKSBhcyBkc3RfZjoKICAgICAgICBkc3RfZi53cml0ZShhY3RpdmVtcV94bWwpCgp1X2ZpbGUuY2xvc2UoKQpnX2ZpbGUuY2xvc2UoKQo=
---
# Source: msgsvc/charts/activemq/templates/deployment.yaml
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: msgsvc-dev-activemq
  labels:
    helm.sh/chart: activemq-0.1.0
    app.kubernetes.io/name: activemq
    app.kubernetes.io/instance: msgsvc-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: wekafs--sdf-k8s01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Source: msgsvc/charts/activemq/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: msgsvc-dev-activemq
  labels:
    helm.sh/chart: activemq-0.1.0
    app.kubernetes.io/name: activemq
    app.kubernetes.io/instance: msgsvc-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 61613
      targetPort: activemq-port
      protocol: TCP
      name: activemq-port
  selector:
    app.kubernetes.io/name: activemq
    app.kubernetes.io/instance: msgsvc-dev
---
# Source: msgsvc/charts/activemq/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgsvc-dev-activemq
  labels:
    helm.sh/chart: activemq-0.1.0
    app.kubernetes.io/name: activemq
    app.kubernetes.io/instance: msgsvc-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: activemq
      app.kubernetes.io/instance: msgsvc-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: activemq
        app.kubernetes.io/instance: msgsvc-dev
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: activemq
          securityContext:
            {}
          image: "ghcr.io/pandawms/panda-activemq:0.0.4"
          command: [ "/bin/sh", "-c" ]
          args:
            - python3 /opt/activemq/sandbox/install_conf.py;
              chmod -R 777 ${ACTIVEMQ_DATA};
              runuser -u activemq -g activemq /opt/activemq/bin/run-activemq-services;
              sleep infinity & wait
          imagePullPolicy: IfNotPresent
          ports:
            - name: activemq-port
              containerPort: 61613
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - name: msgsvc-dev-activemq-data
              mountPath: /appdata/activemq
            - name: msgsvc-dev-activemq-sandbox
              mountPath: /opt/activemq/sandbox
          envFrom:
            - secretRef:
                name: panda-secrets-msgsvc-envs
      volumes:
        - name: msgsvc-dev-activemq-data
          persistentVolumeClaim:
            claimName: msgsvc-dev-activemq
        - name: msgsvc-dev-activemq-sandbox
          configMap:
              name: msgsvc-dev-activemq-sandbox
