# JEDI and server configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-configmap
binaryData:
  {{- range $path, $_ := .Files.Glob "sandbox/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- if .Values.hostcerts.enabled }}
---
# host cert and key
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-certs
binaryData:
  hostcert.pem: |-
    {{ .Files.Get "cert/hostcert.pem" | b64enc }}
  hostkey.pem: |-
    {{ .Files.Get "cert/hostkey.pem" | b64enc }}
  chain.pem: |-
    {{ .Files.Get "cert/chain.pem" | b64enc }}
{{- end }}

---
# env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main.fullname" . }}-env
data:
  # bigmon
  BIGMON_HOST: "{{ .Values.hostName }}"
  BIGMON_NUM_WSGI_PROC: "{{ .Values.httpd.numWSGI }}"
  BIGMON_SECRET_KEY: "{{ .Values.secretKey }}"
  BIGMON_VO: "{{ .Values.vo }}"
  BIGMON_DEPLOYMENT: "{{ .Values.deployment }}"
  # Auth
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "{{ .Values.auth.googleKey }}"
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "{{ .Values.auth.googleSecret }}"
  SOCIAL_AUTH_CERNOIDC_KEY: "{{ .Values.auth.cernKey }}"
  SOCIAL_AUTH_CERNOIDC_SECRET: "{{ .Values.auth.cernSecret }}"
  SOCIAL_AUTH_GITHUB_KEY: "{{ .Values.auth.githubKey }}"
  SOCIAL_AUTH_GITHUB_SECRET: "{{ .Values.auth.githubSecret }}"
  # PandaDB
  PANDA_DB_NAME: "{{ .Values.database.databaseName }}"
  PANDA_DB_HOST: "{{ .Values.database.hostName }}"
  PANDA_DB_PORT: "{{ .Values.database.port }}"
  PANDA_DB_USER: "{{ .Values.database.userName }}"
  PANDA_DB_PASSWORD: "{{ .Values.database.password }}"
  # Rucio
  RUCIO_SERVER_HOST: "{{ .Values.rucio.rucioHost }}"
  RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"
  # CRIC
  CRIC_API_URL: "{{ .Values.cric.apiUrl }}"
  # iDDS
  IDDS_HOST: "{{ .Values.idds.host }}"
  # AWS
  AWS_ACCESS_KEY_ATLAS: "{{ .Values.aws.accessKey }}"
  AWS_SECRET_KEY_ATLAS: "{{ .Values.aws.secretKey }}"

  # HTTP proxy
  {{- if .Values.httpProxy }}
  http_proxy: "{{ .Values.httpProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost"
  {{- end }}
  {{- if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpProxy }}"
  {{- end }}
  {{- else if .Values.httpsProxy }}
  https_proxy: "{{ .Values.httpsProxy }}"
  {{- if .Values.noProxy }}
  no_proxy: "{{ .Values.noProxy }}"
  {{- else }}
  no_proxy: "localhost"
  {{- end }}
  {{- end }}
