{{- if .Values.route.enabled -}}
# for HTTPS
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "main.fullname" . }}-route
  labels:
      {{- include "main.labels" . | nindent 4 }}

spec:
  host: {{ .Values.hostName }}
  to:
    kind: Service
    name: {{ include "main.fullname" . }}
  port:
    targetPort: https
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
