# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"
  sub_secret_name: "iam-mariadb"

main:
  enabled: true

  image:
    # repository: ghcr.io/wguanicedew/panda-k8s-mariadb
    # tag: "0.0.5"
    repository: ghcr.io/wguanicedew/panda-k8s-pandawms-mariadb
    tag: "0.1.5"

  database:
    name: "test-db"

