# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariadb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10.11.3"

database:
  name: "test-db"
  user: "test"

backup:
  path: "/tmp/"

persistentvolume:
  class: manual
  size: 5Gi

