# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:

  iddsServer: panda-idds-dev.cern.ch

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-idds-dev.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: panda-idds-dev.cern.ch
