# pv
{{- if .Values.persistentvolume.create }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "jedi.fullname" . }}
  labels:
      {{- include "jedi.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  capacity:
    storage: {{ .Values.persistentvolume.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentvolume.path }}
---
{{- end }}
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jedi.fullname" . }}
  labels:
    {{- include "jedi.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size }}
  {{- if .Values.persistentvolume.selector }}
  selector:
    matchLabels:
      {{- include "jedi.selectorLabels" . | nindent 6 }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jedi.fullname" . }}
  labels:
    {{- include "jedi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jedi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jedi.selectorLabels" . | nindent 8 }}
    spec:
      hostname:  {{ include "jedi.fullname" . }}-local
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jedi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.autoStart }}
          command: ["/bin/sh", "-c"]
          args:
            - until  /usr/pgsql-*/bin/pg_isready -h ${PANDA_DB_HOST} -p 5432; do echo waiting for database; sleep 2; done;
              cp /opt/panda/sandbox/init-jedi /data/panda/;
              chmod +x /data/panda/init-jedi;
              cp /opt/panda/sandbox/run-jedi-crons /data/panda/;
              chmod +x /data/panda/run-jedi-crons;
              cp /opt/panda/sandbox/* /data/panda/;
              /etc/rc.d/init.d/run-jedi-services;
              sleep infinity & wait
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              - name: {{ include "jedi.fullname" . }}-logs
                mountPath: /var/log/panda
              - name: {{ include "jedi.fullname" . }}-configjson
                mountPath: /opt/panda/etc/config_json
              - name: {{ include "jedi.fullname" . }}-sandbox
                mountPath: /opt/panda/sandbox
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-external-env
            - configMapRef:
                name: {{ .Release.Name }}-server-env
            {{- if .Values.database.password_get }}
            - configMapRef:
                {{- if .Values.database.config_ref }}
                name: {{ .Values.database.config_ref }}
                {{- else }}
                name: {{ .Release.Name }}-postgres-configmap
                {{- end }}
            {{- end }}
          env:
            # set no_proxy since $() is resolved not in envFrom section
            - name: no_proxy
              value: $(no_proxy),$(PANDA_IDDS_HOST)
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "jedi.fullname" . }}-logs
          persistentVolumeClaim:
            claimName: {{ include "jedi.fullname" . }}
        - name: {{ include "jedi.fullname" . }}-sandbox
          projected:
            sources:
              - configMap:
                  name: {{ include "jedi.fullname" . }}-sandbox
              - configMap:
                  name: {{ .Release.Name }}-external-sandbox
              - configMap:
                  name: {{ .Release.Name }}-server-sandbox
        - name: {{ include "jedi.fullname" . }}-configjson
          projected:
            sources:
              - configMap:
                  name: {{ include "jedi.fullname" . }}-configjson
              - configMap:
                  {{- if .Values.server.config_ref }}
                  name: {{ .Values.server.config_ref }}
                  {{- else }}
                  name: {{ .Release.Name }}-server-configjson
                  {{- end }}
