# Default values for msgsvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# whether to use secret
activemq:
  secret:
    enabled: true
    name: "activemq-dev-secret"
