# secret main file

# global values

# affix of instance reference names blah- or -blah
affix: "-FIXME"

auth:
  auth: "oidc"
  authIdToken: "FIXME"
  authVO: "panda_dev"

  oidc:
    audience: "https://pandaserver-doma.cern.ch"
    config_url: "https://panda-iam-doma.cern.ch/.well-known/openid-configuration"
    clients:
      - name: "panda_dev"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin.production"
        client_id: "FIXME"
        client_secret: "FIXME"


msgsvc:
  enabled: true

  basePasswd: "FIXME"

  # accounts
  accounts:
    - "panda"
    - "jedi"
    - "idds"
    - "pilot"

  # message channels. name:write_accounts,read_account
  channels:
    - "idds_panda:idds:panda,jedi"
    - "panda_idds:panda,jedi:idds"
    - "self.jedi_taskstatus:jedi:jedi"
    - "panda_jedi:panda:jedi"
    - "panda_pilot:panda:pilot"
    - "idds.internal:idds:idds"


panda:
  enabled: true

  database:
    password: "FIXME"
    # set only when  using an external database
    dbhost: ""
    name: "panda_db"
    user: "panda"

  # PanDA server ports
  port: "80"
  sslPort: "443"

  # host name of the PanDA server for external access
  hostName: "FIXME"

  verifyHost: "off"
  configRoot: "/tmp/"

harvester:
  enabled: true
  experiment: ""

  # harvester id
  harvesterID: "my-harvester"

  database:
    password: "FIXME"
    # set only when using an external database
    dbhost: ""

  # use stable condor instead of latest
  useStableCondor: false


idds:
  enabled: true

  restPort: 8443

  database:
    name: "idds_db"
    user: "idds"
    password: "FIXME"
    schema: "doma_idds"
    # set only when using an external database
    host: ""


bigmon:
  enabled: true

  hostname: "FIXME"
  numWSGI: "10"
  vo: "FIXME"
  secretKey: "FIXME"
  debugMode: false

  auth:
    providers:
      Google:
        key: "FIXME"
        secret: "FIXME"
      CERN:
        key: "FIXME"
        secret: "FIXME"
      AWS:
        key: "FIXME"
        secret: "FIXME"
      github:
        key: "FIXME"
        secret: "FIXME"

iam:
  enabled: true

  profiles: "prod,registration,oidc"

  base_url: "FIXME"

  database:
    # affix will be used to fill host if it's empty.
    # host: "iam-dev-mariadb"
    host: ""
    name: "iam_db"
    user: "iam"
    password: "FIXME"

  cilogon:
    client_id: "FIXME"
    client_secret: "FIXME"


rucio:
  rucioHost: "sprucio01.sdcc.bnl.gov:443"
  authHost: "sprucio01.sdcc.bnl.gov:443"
  username: "iddsv1"
  password: "FIXME"
  account: "iddsv1"


cric:
  apiUrl: "https://datalake-cric.cern.ch/api/atlas/pandaqueue/query/?json"


proxy:
  httpProxy: ""
  httpsProxy: ""
