# secret main file

# global values

# affix of instance reference names blah- or -blah
affix: "-FIXME"

auth:
  auth: "oidc"
  authIdToken: "FIXME"
  authVO: "panda_dev"

  oidc:
    audience: "https://pandaserver-doma.cern.ch"
    config_url: "https://panda-iam-doma.cern.ch/.well-known/openid-configuration"
    clients:
      - name: "panda_dev"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin"
        client_id: "FIXME"
        client_secret: "FIXME"
      - name: "Rubin.production"
        client_id: "FIXME"
        client_secret: "FIXME"


msgsvc:
  enabled: true

  basePasswd: "FIXME"

  # accounts
  accounts:
    - "panda"
    - "jedi"
    - "idds"
    - "pilot"

  # message channels. name:write_accounts,read_account
  channels:
    - "idds_panda:idds:panda,jedi"
    - "panda_idds:panda,jedi:idds"
    - "self.jedi_taskstatus:jedi:jedi"
    - "panda_jedi:panda:jedi"
    - "panda_pilot:panda:pilot"
    - "idds.internal:idds:idds"


panda:
  enabled: true

  database:
    backend: "postgres" # or oraclex
    password: "FIXME"
    # set hostname only when using an external database
    dbhost: ""
    dbport: "5432"
    name: "panda_db"
    user: "panda"

  # PanDA server ports
  port: "80"
  sslPort: "443"

  # host name of the PanDA server for external access
  hostName: "FIXME"

  verifyHost: "off"
  configRoot: "/tmp/"

harvester:
  enabled: true
  experiment: ""

  # harvester id
  harvesterID: "my-harvester"

  database:
    password: "FIXME"
    # set only when using an external database
    # dbhost: "localhost"
    dbhost: ""

  # condor channel: 9, stable, or latest
  condorChannel: "latest"


idds:
  enabled: true

  restPort: 8443

  database:
    name: "idds_db"
    user: "idds"
    password: "FIXME"
    schema: "doma_idds"
    # set hostname only when using an external database
    host: ""
    port: "5432"


bigmon:
  enabled: true

  base_url: "FIXME"

  hostname: "FIXME"
  numWSGI: "10"
  vo: "FIXME"
  secretKey: "FIXME"
  debugMode: false

  # logs provider - either rucio or cric
  logs_provider: "FIXME"

  auth:
    providers:
      Google:
        key: "FIXME"
        secret: "FIXME"
      CERNOIDC:
        key: "FIXME"
        secret: "FIXME"
      github:
        key: "FIXME"
        secret: "FIXME"
      indigoiam:
        key: "FIXME"
        secret: "FIXME"
        basePath: "FIXME"

  # set prmonLocation: "" to use rucio download to fetch prmon files
  prmonLocation: "https://storage.googleapis.com/drp-us-central1-logging/logs/{queue_name}/PandaJob_{panda_id}"


iam:
  enabled: true

  profiles: "prod,registration,oidc"

  base_url: "FIXME"
  port: 8443

  database:
    # affix will be used to fill host if it's empty.
    # host: "iam-dev-mariadb"
    host: ""
    name: "iam_db"
    user: "iam"
    password: "FIXME"

  cilogon:
    client_id: "FIXME"
    client_secret: "FIXME"


rucio:
  rucioHost: "sprucio01.sdcc.bnl.gov:443"
  authHost: "sprucio01.sdcc.bnl.gov:443"
  username: "iddsv1"
  password: "FIXME"
  account: "iddsv1"


cric:
  # real CRIC
  real: true

  # URLs
  costMetrix: ""
  ddmBlackList: "https://datalake-cric.cern.ch/api/atlas/ddmendpointstatus/query/?json&activity=write_wan&fstate=OFF"
  ddmEndpoints: "https://datalake-cric.cern.ch/api/atlas/ddmendpoint/query/?json"
  schedConfig: "https://datalake-cric.cern.ch/api/atlas/pandaqueue/query/?json"
  sites: "https://datalake-cric.cern.ch/api/atlas/site/query/?json"
  objectStores: "https://datalake-cric.cern.ch/api/atlas/ddmendpoint/query/?json&state=ACTIVE&site_state=ACTIVE&preset=dict&json_pretty=1&type[]=OS_LOGS&type[]=OS_ES"

object_store:
  host_name: "FIXME"
  port: 443
  bucket_name: "FIXME"
  access_key: "FIXME"
  secret_key: "FIXME"


proxy:
  httpProxy: ""
  httpsProxy: ""
